#!/bin/sh
_CONDA_ROOT="/packages/apps/mamba/1.5.8"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
\. /packages/apps/mamba/common/activate-tracking.sh
